---
name: aardappel

on:
  push:
    paths:
      - '**.txt'
      - '.github/workflows/aardappel.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '.github/workflows/aardappel.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

jobs:
  get-thing:
    runs-on: ubuntu-2022
    
    output:
        thing: ${{ steps.thing.outputs.THING }}
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - id: thing
          name: Stuff Thing
          run: |
            echo '::set-output name=THING::17'
    
  mainjob:
    runs-on: {{'matrix.os'}}
    
    needs: [ get-thing ]
    
    strategy:
    fail-fast: true
    matrix:
        os: [ windows-2022 ]
        zed: [ a, b, c]
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Do Thing
          run: |
            echo 'YES: ${{ needs.get-semver.outputs.user }}'
