---
name: aardbei

on:
  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/aardbei.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/aardbei.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  workflow_call:
    outputs:
      thething:
        description: "THE MOST RANDOM NUMBER"
        value: ${{ jobs.get-thing.outputs.thing }}

jobs:
  get-thing:
    runs-on: ubuntu-20.04
    
    outputs:
        thing: ${{ steps.thing.outputs.THING }}
    
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - id: thing
          name: Stuff Thing
          run: |
            echo 'THING=17' >> $GITHUB_OUTPUT

  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ get-thing ]
    
    strategy:
      fail-fast: true
      matrix:
        os: [ windows-2022 ]
        zed: [ a ]

    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Do Thing
          run: |
            echo 'YES: ${{ needs.get-thing.outputs.THING }}'
