name: Automerge Main To Branch

on:
    workflow_dispatch:
    schedule:
    -   cron: '15 5 * * 2-6'

jobs:
    merge:
        runs-on: ubuntu-latest

    steps:
    -   name: Checkout
        uses: actions/checkout@v3

    -   name: Setup Python
        uses: actions/setup-python@v4

    -   name: Merge Branches With Main
        shell: python
        run: |
            from subprocess import run
            def rrun(cmd):
                res = run(cmd.split(" "), shell=True, capture_output=True, text=True)
                if res.returncode != 0:
                    print("FAILED AT:")
                    print(cmd)
                    print(res.stderr)
                    exit(1)
                return res.stdout
            def getBranches():
                get_branches=rrun("git branch -r --format=%(refname:short)")
                return [x.split("/")[1] for x in get_branches.stdout.split("\n") if x]
            rrun("git config pull.rebase false")
            commands_per_branch = [
                "git checkout $BRANCH",
                "git pull",
                "git merge main",
                "git push",
            ]
            for branch in getBranches():
                # TODO: Also for the latest version branch.
                if branch == "main" or not branch.startsWith("CURA-"):
                    continue
                try:
                    ticket_no = int(branch.split("-")[1])
                except:
                    continue
                if ticket_no < 10000:
                    continue
                for cmd in commands_per_branch:
                    rrun(cmd.replace("$BRANCH", branch))                
