---
name: banang

on:

  workflow_dispatch:
    inputs:
        blah_blah_blah:
            description: ":banana: :apple: :rocket:"
            type: boolean
            default: true
            required: true

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

jobs:
  my_aardbei:
    uses: ./.github/workflows/aardbei.yml
    
  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ my_aardbei ]
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        zed: [x, y]
        exclude:
            - zed: ${{ inputs.blah_blah_blah && 'x' || '' }}
            - zed: ${{ inputs.blah_blah_blah && '' || 'y' }}

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: What's That OS String?
          run: |
            echo "OS_NAME=${{ (matrix.os == 'ninzononzenze' && 'xyz') || (matrix.os == 'windows_2022' && 'WINBDOWS_$(uuidgen)') || (matrix.os == 'blaaaah' && 'bloeh') || 'os_name_missing_$(uuidgen)' }}" >> $GITHUB_ENV

        - name: Do Thing Also
          run: |
            echo 'PROGRESS GOES BONK: $RANDOM | ${{ needs.my_aardbei.outputs.thething }} | $OS_NAME | ${{ inputs.blah_blah_blah }}'
