---
name: banang

on:

  workflow_dispatch:
    inputs:
        all_platforms:
            description: "Platforms To Build For"
            type: string
            default: '[windows-2022, ubuntu-20.04]'
            required: true

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

env:
    OS_NAME: 'unkown-os'

jobs:
  my_aardbei:
    uses: ./.github/workflows/aardbei.yml

  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ my_aardbei ]
    
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.all_platforms) }}
        zed: [x, y]

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: What's That OS String?
          run: |
            echo "OS_NAME=${{ (matrix.os == 'ubuntu-22.04' && 'LNIUX') || (matrix.os == 'windows-2022' && 'WINBDOWS') || (matrix.os == 'blaaaah' && 'bloeh') || matrix.os }}" >> $GITHUB_ENV

        - name: Do Thing Also
          run: |
            echo 'PROGRESS GOES BONK: $RANDOM | ${{ needs.my_aardbei.outputs.thething }} | ${{ env.OS_NAME }} | ${{ inputs.all_platforms }}'
