---
name: banang

on:

  workflow_dispatch:
    inputs:
        blah_blah_blah:
            description: ":banana: :apple: :rocket:"
            type: boolean
            default: true
            required: true

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

jobs:
  my_aardbei:
    uses: ./.github/workflows/aardbei.yml
    
  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ my_aardbei ]
    
    strategy:
        fail-fast: false
        matrix:
            include:
                -   { os: windows-2022, zed: x }
                    if: {{ inputs.blah_blah_blah }}
                -   { os: windows-2022, zed: y }
                    if: {{ ! inputs.blah_blah_blah }}
            #os: [ windows-2022 ]
            #zed: [ x, y ]

    steps:
        - name: Checkout
          uses: actions/checkout@v3
        
        - name: Do Thing Also
          run: |
            echo 'PROGRESS GOES BONK: ${{ needs.my_aardbei.outputs.thething }} ${{ inputs.blah_blah_blah }}'
