---
name: banang

on:

  workflow_dispatch:
    inputs:
        winblah:
            description: "WIN16"
            type: boolean
            default: true
            required: true
        ublah:
            description: "TUX"
            type: boolean
            default: false
            required: true

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

env:
    OS_NAME: 'unkown-os'

jobs:
  my_aardbei:
    uses: ./.github/workflows/aardbei.yml

  set_os:
    runs-on: ubuntu-latest
    outputs:
        matrix: ${{ steps.ososos.outputs.matrix }}
    steps:
        - name: OS/2 Warp 4.1
          id: ososos
          run: |
            echo "matrix=${{ join([(inputs.ublah && '{name: ubuntu-22.04}' || '{}'), (inputs.winblah && '{name: windows-2022}' || '{}')].*.name, ',')}}" >> $GITHUB_OUTPUT

  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ set_os, my_aardbei ]
    
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(needs.set_os.outputs.matrix) }}
        zed: [x, y]

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: What's That OS String?
          run: |
            echo "OS_NAME=${{ (matrix.os == 'ubuntu-22.04' && 'LNIUX') || (matrix.os == 'windows-2022' && 'WINBDOWS') || (matrix.os == 'blaaaah' && 'bloeh') || matrix.os }}" >> $GITHUB_ENV

        - name: Do Thing Also
          run: |
            echo 'PROGRESS GOES BONK: $RANDOM | ${{ needs.my_aardbei.outputs.thething }} | ${{ env.OS_NAME }} | ${{ inputs.blah_blah_blah }}'
