---
name: banang

on:

  workflow_dispatch:

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - nope
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

env:
    OS_NAME: 'unkown-os'

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file

      - name: Did it actually do something with the files?
        run: |
            git status

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed > 0
        run: echo "Some files failed the linting checks!"
        # for actual deployment
        # run: exit 1

  #windows_aardbei:
  #  uses: ./.github/workflows/aardbei.yml

  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      aaa: [windows-2022]

  #  with:
  #     aaa: ${{ matrix.aaa }}

  #linux_aardbei:
  #    uses: ./.github/workflows/aardbei.yml
  #    with:
  #      aaa: 'ubuntu-latest'

  #mainjob:
  #  runs-on: ${{ matrix.os }}

  #  needs: [ windows_aardbei ]

  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      os: [windows-2022]
  #      zed: [x]

  #  steps:
  #      - name: Checkout
  #        uses: actions/checkout@v3

  #      - name: What's That OS String?
  #        run: |
  #          echo "OS_NAME=${{ (matrix.os == 'ubuntu-22.04' && 'LNIUX') || (matrix.os == 'windows-2022' && 'WINBDOWS') || (matrix.os == 'blaaaah' && 'bloeh') || matrix.os }}" >> $GITHUB_ENV

  #      - name: Do Thing Also
  #        run: |
  #          echo 'PROGRESS GOES BONK: $RANDOM | ${{ needs.windows_aardbei.outputs.thething }} | ${{ env.OS_NAME }} | ${{ inputs.all_platforms }}'
