---
name: banang

on:

  workflow_dispatch:

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - nope
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/banang.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

env:
    OS_NAME: 'unkown-os'

jobs:
  windows_aardbei:
    uses: ./.github/workflows/aardbei.yml

    strategy:
      fail-fast: false
      matrix:
        aaa: [windows-2022]

    with:
        aaa: ${{ matrix.aaa }}

  linux_aardbei:
      uses: ./.github/workflows/aardbei.yml
      with:
        aaa: 'ubuntu-latest'

  mainjob:
    runs-on: ${{ matrix.os }}
    
    needs: [ windows_aardbei ]
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        zed: [x]

    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: What's That OS String?
          run: |
            echo "OS_NAME=${{ (matrix.os == 'ubuntu-22.04' && 'LNIUX') || (matrix.os == 'windows-2022' && 'WINBDOWS') || (matrix.os == 'blaaaah' && 'bloeh') || matrix.os }}" >> $GITHUB_ENV

        - name: Do Thing Also
          run: |
            echo 'PROGRESS GOES BONK: $RANDOM | ${{ needs.windows_aardbei.outputs.thething }} | ${{ env.OS_NAME }} | ${{ inputs.all_platforms }}'
