---
name: citroen

on:

  workflow_dispatch:

  push:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/citroen.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

  pull_request:
    paths:
      - '**.txt'
      - '**.yml'
      - '.github/workflows/citroen.yml'
    branches:
      - brain
    tags:
      - '![1-9].[0-9]+*'

jobs:
  repro:
    runs-on: ubuntu-22.04
        
    steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Pretend Benchmark
          run: |
            import json
            data = [
                {
                "name": "Aaa",
                "unit": "Squerps",
                "value": 11.5,
                },
                {
                "name": "Bbb",
                "unit": "Blorf",
                "value": 40,
                },
            ]
            datastr = json.dumps(data)
            with open("output.json", "w") as file:
                file.write(datastr)
          shell: python

        - name: Store benchmark result
          uses: benchmark-action/github-action-benchmark@v1
          with:
            name: My Project BLEH Benchmark
            output-file-path: output.json
            tool: customBiggerIsBetter
            # Access token to deploy GitHub Pages branch
            github-token: ${{ secrets.GITHUB_TOKEN }}
            # Push and deploy GitHub pages branch automatically
            auto-push: true
